version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: ignite-call-my-sql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ignite_call
      MYSQL_USER: podman
      MYSQL_PASSWORD: podman

volumes:
  mysql_data:
    name: ignite-call-volume
